[[constraint]]
  name = "github.com/casualcode/soap"
  branch = "master"

[[constraint]]
  name = "github.com/devimteam/wsdl2go"
  revision = "7ed0da94ff4f278c98478381bdb7af3080d5be03"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"