[[constraint]]
  name = "github.com/casualcode/soap"
  branch = "master"

[[constraint]]
  name = "github.com/devimteam/wsdl2go"
  revision = "5c4e6c7ba9d9355bba952997eb0c639cb90f672e"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"